# Pandas
- Powerful for Data analysis and Data science
- Uses data frames and series
- To deal with missing data
- Insert and delete a column 
- Data alignment
- Group by
- Subsetting
- Merging
- Reshaping
- Pivoting
- Time series analysis

In [151]:
import pandas as pd

In [152]:
pd.__version__

'1.4.2'

In [153]:
Store1 = pd.read_csv(r'C:\Users\sruja\Sample - Superstore_Orders.csv')

In [154]:
Store1

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77095,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [155]:
Store1.shape
# Gives rows and columns

(10194, 19)

In [156]:
len(Store1)
# Gives only rows

10194

In [157]:
# To see column names
Store1.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [158]:
len(Store1.columns)
# To get the number of columns

19

In [159]:
type(Store1)

pandas.core.frame.DataFrame

In [160]:
Store1.info()

# Information of the data frame
# A dataset contains both numerical and categorical data. 
# By default the system considers categorical data as an object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        10194 non-null  object
 1   City            10194 non-null  object
 2   Country/Region  10194 non-null  object
 3   Customer Name   10194 non-null  object
 4   Manufacturer    10194 non-null  object
 5   Order Date      10194 non-null  object
 6   Order ID        10194 non-null  object
 7   Postal Code     10194 non-null  object
 8   Product Name    10194 non-null  object
 9   Region          10194 non-null  object
 10  Segment         10194 non-null  object
 11  Ship Date       10194 non-null  object
 12  Ship Mode       10194 non-null  object
 13  State/Province  10194 non-null  object
 14  Sub-Category    10194 non-null  object
 15  Discount        10194 non-null  float64
 16  Profit          10194 non-null  float64
 17  Quantity        10194 non-null  int64
 18  Sales           10194 non-null  float64
dtypes: float64(3), int64(1), object(15)
memory usage: 1.5+ MB

In [161]:
Store1.info
# Note the difference between info and info()

<bound method DataFrame.info of               Category           City Country/Region      Customer Name  \
0      Office Supplies        Houston  United States      Darren Powers
1      Office Supplies     Naperville  United States      Phillina Ober
2      Office Supplies     Naperville  United States      Phillina Ober
3      Office Supplies     Naperville  United States      Phillina Ober
4      Office Supplies   Philadelphia  United States         Mick Brown
...                ...            ...            ...                ...
10189  Office Supplies  New York City  United States  Patrick O'Donnell
10190  Office Supplies      Fairfield  United States         Erica Bern
10191  Office Supplies       Loveland  United States      Jill Matthias
10192       Technology  New York City  United States  Patrick O'Donnell
10193  Office Supplies  Charlottetown         Canada        Harry Olson

       Manufacturer  Order Date        Order ID Postal Code  \
0      Message Book  03-01-2020  US-2020-103800       77095
1               GBC  04-01-2020  US-2020-112326       60540
2             Avery  04-01-2020  US-2020-112326       60540
3             SAFCO  04-01-2020  US-2020-112326       60540
4             Avery  05-01-2020  US-2020-141817       19143
...             ...         ...             ...         ...
10189  Wilson Jones  30-12-2023  US-2023-143259       10009
10190           GBC  30-12-2023  US-2023-115427       94533
10191         Other  30-12-2023  US-2023-156720       80538
10192         Other  30-12-2023  US-2023-143259       10009
10193  Wilson Jones  30-12-2023  CA-2023-143500         C0A

                                            Product Name   Region  \
0      Message Book, Wirebound, Four 5 1/2" X 4" Form...  Central
1             GBC Standard Plastic Binding Systems Combs  Central
2                                              Avery 508  Central
3                          SAFCO Boltless Steel Shelving  Central
4      Avery Hi-Liter EverBold Pen Style Fluorescent ...     East
...                                                  ...      ...
10189               Wilson Jones Legal Size Ring Binders     East
10190                                 GBC Binding covers     West
10191                                Bagged Rubber Bands     West
10192                          Gear Head AU3700S Headset     East
10193                        Wilson Jones Impact Binders     East

           Segment   Ship Date       Ship Mode        State/Province  \
0         Consumer  07-01-2020  Standard Class                 Texas
1      Home Office  08-01-2020  Standard Class              Illinois
2      Home Office  08-01-2020  Standard Class              Illinois
3      Home Office  08-01-2020  Standard Class              Illinois
4         Consumer  12-01-2020  Standard Class          Pennsylvania
...            ...         ...             ...                   ...
10189     Consumer  03-01-2024  Standard Class              New York
10190    Corporate  03-01-2024  Standard Class            California
10191     Consumer  03-01-2024  Standard Class              Colorado
10192     Consumer  03-01-2024  Standard Class              New York
10193     Consumer  03-01-2024  Standard Class  Prince Edward Island

      Sub-Category  Discount   Profit  Quantity    Sales
0            Paper       0.2   5.5512         2   16.448
1          Binders       0.8  -5.4870         2    3.540
2           Labels       0.2   4.2717         3   11.784
3          Storage       0.2 -64.7748         3  272.736
4              Art       0.2   4.8840         3   19.536
...            ...       ...      ...       ...      ...
10189      Binders       0.2  19.7910         3   52.776
10190      Binders       0.2   6.4750         2   20.720
10191    Fasteners       0.2  -0.6048         3    3.024
10192       Phones       0.0   2.7279         7   90.930
10193      Binders       0.2  -0.6048         3    3.024

[10194 rows x 19 columns]>

In [162]:
Store1.isnull()
# False implies that there are no missing values

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10190,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10191,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10192,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10193,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [163]:
Store1.isnull().sum()
# Here we can see the total number of null values

Category          0
City              0
Country/Region    0
Customer Name     0
Manufacturer      0
Order Date        0
Order ID          0
Postal Code       0
Product Name      0
Region            0
Segment           0
Ship Date         0
Ship Mode         0
State/Province    0
Sub-Category      0
Discount          0
Profit            0
Quantity          0
Sales             0
dtype: int64

Note: 
- Null values must not be removed, but we need to fill the data using EDA (Missing value treatment, etc) and transformers
- Transformers - transfer learning in nlp - bert, gpt, t5 model
- Transfer learning in computer vision - imagenet, resnet 
- Raw data - the dataset that contains missing/incorrect info

In [164]:
Store1.isna()
# Also used to check missing values

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10190,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10191,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10192,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10193,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [165]:
Store1.isna().sum()

Category          0
City              0
Country/Region    0
Customer Name     0
Manufacturer      0
Order Date        0
Order ID          0
Postal Code       0
Product Name      0
Region            0
Segment           0
Ship Date         0
Ship Mode         0
State/Province    0
Sub-Category      0
Discount          0
Profit            0
Quantity          0
Sales             0
dtype: int64

In [166]:
Store1.head()
# Displays the top 5 records

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77095,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536

In [167]:
Store1.head(6)
# Displays the top 6 records

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77095,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
5,Furniture,Henderson,United States,Maria Etezadi,Global,06-01-2020,US-2020-167199,42420,Global Deluxe High-Back Manager's Chair,South,Home Office,10-01-2020,Standard Class,Kentucky,Chairs,0.0,746.4078,9,2573.820

In [168]:
Store1.tail()
# Displays the bottom 5 records

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [169]:
Store1[10:21]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10,Office Supplies,Henderson,United States,Maria Etezadi,Southworth,06-01-2020,US-2020-167199,42420,Southworth 25% Cotton Granite Paper & Envelopes,South,Home Office,10-01-2020,Standard Class,Kentucky,Paper,0.0,3.0084,1,6.540
11,Office Supplies,Los Angeles,United States,Lycoris Saunders,Xerox,06-01-2020,US-2020-130813,90049,Xerox 225,West,Consumer,08-01-2020,Second Class,California,Paper,0.0,9.3312,3,19.440
12,Technology,Henderson,United States,Maria Etezadi,Other,06-01-2020,US-2020-167199,42420,Wireless Extenders zBoost YX545 SOHO Signal Bo...,South,Home Office,10-01-2020,Standard Class,Kentucky,Phones,0.0,204.1092,4,755.960
13,Technology,Henderson,United States,Maria Etezadi,GE,06-01-2020,US-2020-167199,42420,GE 30524EE4,South,Home Office,10-01-2020,Standard Class,Kentucky,Phones,0.0,113.6742,2,391.980
14,Furniture,Huntsville,United States,Vivek Sundaresam,Howard Miller,07-01-2020,US-2020-105417,77340,"Howard Miller 14-1/2"" Diameter Chrome Round Wa...",Central,Consumer,12-01-2020,Standard Class,Texas,Furnishings,0.6,-53.7096,3,76.728
15,Office Supplies,Huntsville,United States,Vivek Sundaresam,Acco,07-01-2020,US-2020-105417,77340,Acco Four Pocket Poly Ring Binder with Label H...,Central,Consumer,12-01-2020,Standard Class,Texas,Binders,0.8,-18.2525,7,10.430
16,Office Supplies,Laredo,United States,Melanie Seite,Newell,09-01-2020,US-2020-135405,78041,Newell 312,Central,Consumer,13-01-2020,Standard Class,Texas,Art,0.2,1.1680,2,9.344
17,Technology,Laredo,United States,Melanie Seite,Memorex,09-01-2020,US-2020-135405,78041,Memorex Micro Travel Drive 8 GB,Central,Consumer,13-01-2020,Standard Class,Texas,Accessories,0.2,9.7500,3,31.200
18,Furniture,Springfield,United States,Anthony Jacobs,Howard Miller,10-01-2020,US-2020-149020,22153,"Howard Miller 11-1/2"" Diameter Ridgewood Wall ...",South,Corporate,15-01-2020,Standard Class,Virginia,Furnishings,0.0,21.2954,1,51.940
19,Office Supplies,Springfield,United States,Anthony Jacobs,Avery,10-01-2020,US-2020-149020,22153,Avery 482,South,Corporate,15-01-2020,Standard Class,Virginia,Labels,0.0,1.3583,1,2.890
20,Furniture,Dover,United States,Seth Vernon,DAX,11-01-2020,US-2020-130092,19901,"DAX Value U-Channel Document Frames, Easel Back",East,Consumer,14-01-2020,First Class,Delaware,Furnishings,0.0,3.0814,2,9.940

In [170]:
Store1[::-1]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77095,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448

In [171]:
Store1[::10]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77095,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
10,Office Supplies,Henderson,United States,Maria Etezadi,Southworth,06-01-2020,US-2020-167199,42420,Southworth 25% Cotton Granite Paper & Envelopes,South,Home Office,10-01-2020,Standard Class,Kentucky,Paper,0.0,3.0084,1,6.540
20,Furniture,Dover,United States,Seth Vernon,DAX,11-01-2020,US-2020-130092,19901,"DAX Value U-Channel Document Frames, Easel Back",East,Consumer,14-01-2020,First Class,Delaware,Furnishings,0.0,3.0814,2,9.940
30,Office Supplies,San Francisco,United States,Brian Dahlen,Tennsco,13-01-2020,US-2020-157147,94109,Tennsco 6- and 18-Compartment Lockers,West,Consumer,18-01-2020,Standard Class,California,Storage,0.0,238.6530,5,1325.850
40,Office Supplies,Scottsdale,United States,Toby Swindell,GBC,19-01-2020,US-2020-146591,85254,"GBC Standard Recycled Report Covers, Clear Pla...",West,Consumer,20-01-2020,First Class,Arizona,Binders,0.7,-23.7160,10,32.340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10150,Office Supplies,Newark,United States,Dan Reichenbach,BIC,27-12-2023,US-2023-134404,43055,BIC Brite Liner Highlighters,East,Corporate,27-12-2023,Same Day,Ohio,Art,0.2,3.6432,4,13.248
10160,Office Supplies,New York City,United States,Jennifer Ferguson,Storex,28-12-2023,US-2023-164826,10024,Storex Dura Pro Binders,East,Consumer,04-01-2024,Standard Class,New York,Binders,0.2,11.2266,7,33.264
10170,Technology,New York City,United States,Jennifer Ferguson,Other,28-12-2023,US-2023-164826,10024,Cush Cases Heavy Duty Rugged Cover Case for Sa...,East,Consumer,04-01-2024,Standard Class,New York,Phones,0.0,4.0095,3,14.850
10180,Office Supplies,New York City,United States,Michael Chen,Other,29-12-2023,US-2023-102638,10035,Ideal Clamps,East,Consumer,31-12-2023,First Class,New York,Fasteners,0.0,2.9547,3,6.030
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720

In [172]:
# To split categorical and numerical data
Store1['Category']

0        Office Supplies
1        Office Supplies
2        Office Supplies
3        Office Supplies
4        Office Supplies
              ...
10189    Office Supplies
10190    Office Supplies
10191    Office Supplies
10192         Technology
10193    Office Supplies
Name: Category, Length: 10194, dtype: object

In [173]:
Store1[['Category','City']]

              Category           City
0      Office Supplies        Houston
1      Office Supplies     Naperville
2      Office Supplies     Naperville
3      Office Supplies     Naperville
4      Office Supplies   Philadelphia
...                ...            ...
10189  Office Supplies  New York City
10190  Office Supplies      Fairfield
10191  Office Supplies       Loveland
10192       Technology  New York City
10193  Office Supplies  Charlottetown

[10194 rows x 2 columns]

In [174]:
Store1.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [175]:
# To split categorical data
Store1_categorical = Store1[['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category']]

In [176]:
# To split numerical data
Store1_numerical = Store1[['Discount', 'Profit', 'Quantity', 'Sales']]

In [177]:
print(len(Store1.columns))
print(len(Store1_categorical.columns))
print(len(Store1_numerical.columns))

19
15
4

In [178]:
Store1_categorical.head(1)

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77095,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper

In [179]:
Store1_numerical.head(1)

   Discount  Profit  Quantity   Sales
0       0.2  5.5512         2  16.448

In [180]:
Store1_categorical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        10194 non-null  object
 1   City            10194 non-null  object
 2   Country/Region  10194 non-null  object
 3   Customer Name   10194 non-null  object
 4   Manufacturer    10194 non-null  object
 5   Order Date      10194 non-null  object
 6   Order ID        10194 non-null  object
 7   Postal Code     10194 non-null  object
 8   Product Name    10194 non-null  object
 9   Region          10194 non-null  object
 10  Segment         10194 non-null  object
 11  Ship Date       10194 non-null  object
 12  Ship Mode       10194 non-null  object
 13  State/Province  10194 non-null  object
 14  Sub-Category    10194 non-null  object
dtypes: object(15)
memory usage: 1.2+ MB

In [181]:
Store1_numerical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Discount  10194 non-null  float64
 1   Profit    10194 non-null  float64
 2   Quantity  10194 non-null  int64
 3   Sales     10194 non-null  float64
dtypes: float64(3), int64(1)
memory usage: 318.7 KB

### Statistical information

In [182]:
Store1_categorical.describe()
# For categorical data, mean cannot be obtained. Mode can be obtained.

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category
count,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194
unique,3,542,2,800,183,1242,5111,654,1849,4,3,1338,4,59,17
top,Office Supplies,New York City,United States,William Brown,Other,05-09-2022,US-2023-100111,10035,Staples,West,Consumer,16-12-2021,Standard Class,California,Binders
freq,6128,915,9994,41,1940,38,14,263,50,3253,5281,38,6120,2001,1548

In [183]:
Store1_numerical.describe()

           Discount        Profit      Quantity         Sales
count  10194.000000  10194.000000  10194.000000  10194.000000
mean       0.155385     28.673417      3.791838    228.225854
std        0.206249    232.465115      2.228317    619.906839
min        0.000000  -6599.978000      1.000000      0.444000
25%        0.000000      1.760800      2.000000     17.220000
50%        0.200000      8.690000      3.000000     53.910000
75%        0.200000     29.297925      5.000000    209.500000
max        0.800000   8399.976000     14.000000  22638.480000

In [184]:
Store1.describe()

           Discount        Profit      Quantity         Sales
count  10194.000000  10194.000000  10194.000000  10194.000000
mean       0.155385     28.673417      3.791838    228.225854
std        0.206249    232.465115      2.228317    619.906839
min        0.000000  -6599.978000      1.000000      0.444000
25%        0.000000      1.760800      2.000000     17.220000
50%        0.200000      8.690000      3.000000     53.910000
75%        0.200000     29.297925      5.000000    209.500000
max        0.800000   8399.976000     14.000000  22638.480000

**Note that by default describe function considers only numerical information. If we want to use the describe function over categorical data, we need to split the dataset into categorical and apply describe**

In [185]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import re
import math

    To apply any theme
     !pip install --upgrade jupyterthemes
     jt -t oceans16
    To reset theme
     !jt -r

### Creating Pandas series from NumPy array

In [186]:
a1 = np.arange(11,21)
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [225]:
s1 = pd.Series(a1)
s1

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
9    20
dtype: int32

In [188]:
# Datatype of series
s1.dtype

dtype('int32')

In [189]:
# Returns the number of elements in the underlying data
s1.size

10

In [190]:
s1.nbytes

40

In [191]:
s1.shape

(10,)

In [192]:
s1.ndim

1

In [193]:
len(s1)

10

In [194]:
s1.count()

10

In [195]:
# Modifying index of a series
s1.index = np.array(['a','b','c','d','e','f','g','h','i','j'])
s1

a    11
b    12
c    13
d    14
e    15
f    16
g    17
h    18
i    19
j    20
dtype: int32

In [196]:
# Creating series using random and range functions
a2 = np.random.random(10)
i2 = np.arange(1,11)
s2 = pd.Series(a2,i2)
s2

1     0.984008
2     0.352991
3     0.200540
4     0.598806
5     0.796395
6     0.287232
7     0.612291
8     0.456538
9     0.814506
10    0.040724
dtype: float64

In [197]:
# Creating series using dict
dict1 = {'a':1, 'b':2, 'c':3, 'd':4}
s3 = pd.Series(dict1)
s3

a    1
b    2
c    3
d    4
dtype: int64

In [198]:
pd.Series(1,index = [1,2,3,4,5,6,7,8,9,10])

1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
dtype: int64

### Slicing

In [200]:
s1[:]

a    11
b    12
c    13
d    14
e    15
f    16
g    17
h    18
i    19
j    20
dtype: int32

In [202]:
# First three elements
s1[0:3]

a    11
b    12
c    13
dtype: int32

In [204]:
# Last element
s1[-1:]

j    20
dtype: int32

In [207]:
# Return all elements except last one
s1[:-1]

a    11
b    12
c    13
d    14
e    15
f    16
g    17
h    18
i    19
dtype: int32

In [206]:
# Return all elements except last 3
s1[:-3]

a    11
b    12
c    13
d    14
e    15
f    16
g    17
dtype: int32

In [209]:
s1[-4:-2]

g    17
h    18
dtype: int32

### Append Series

In [210]:
print(s1)
print(s2)

a    11
b    12
c    13
d    14
e    15
f    16
g    17
h    18
i    19
j    20
dtype: int32
1     0.984008
2     0.352991
3     0.200540
4     0.598806
5     0.796395
6     0.287232
7     0.612291
8     0.456538
9     0.814506
10    0.040724
dtype: float64

In [211]:
s2.append(s1)

C:\Users\sruja\AppData\Local\Temp\ipykernel_32484\2685623379.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s2.append(s1)

1      0.984008
2      0.352991
3      0.200540
4      0.598806
5      0.796395
6      0.287232
7      0.612291
8      0.456538
9      0.814506
10     0.040724
a     11.000000
b     12.000000
c     13.000000
d     14.000000
e     15.000000
f     16.000000
g     17.000000
h     18.000000
i     19.000000
j     20.000000
dtype: float64

In [230]:
s3 = pd.Series(np.arange(20,30),np.arange(1,11))
s3

1     20
2     21
3     22
4     23
5     24
6     25
7     26
8     27
9     28
10    29
dtype: int32

In [232]:
print(s3.drop(1))
s3

2     21
3     22
4     23
5     24
6     25
7     26
8     27
9     28
10    29
dtype: int32

1     20
2     21
3     22
4     23
5     24
6     25
7     26
8     27
9     28
10    29
dtype: int32

In [233]:
print(s3.drop(2, inplace = False))
print(s3)

1     20
3     22
4     23
5     24
6     25
7     26
8     27
9     28
10    29
dtype: int32
1     20
2     21
3     22
4     23
5     24
6     25
7     26
8     27
9     28
10    29
dtype: int32

In [234]:
print(s3.drop(2, inplace = True))
print(s3)

None
1     20
3     22
4     23
5     24
6     25
7     26
8     27
9     28
10    29
dtype: int32

In [235]:
s4 = s3.append(pd.Series({11:30}))

C:\Users\sruja\AppData\Local\Temp\ipykernel_32484\796214566.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s4 = s3.append(pd.Series({11:30}))

In [236]:
s4

1     20
3     22
4     23
5     24
6     25
7     26
8     27
9     28
10    29
11    30
dtype: int64

### Operations

In [237]:
print(s1)
print(s2)

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
9    20
dtype: int32
1     0.984008
2     0.352991
3     0.200540
4     0.598806
5     0.796395
6     0.287232
7     0.612291
8     0.456538
9     0.814506
10    0.040724
dtype: float64

In [238]:
s1.add(s2)
# Note that addition is performed if index is the same, else NaN (Not a number) is returned

0           NaN
1     12.984008
2     13.352991
3     14.200540
4     15.598806
5     16.796395
6     17.287232
7     18.612291
8     19.456538
9     20.814506
10          NaN
dtype: float64

In [240]:
s1.add(10)

0    21
1    22
2    23
3    24
4    25
5    26
6    27
7    28
8    29
9    30
dtype: int32

In [239]:
s1.sub(s2)

0           NaN
1     11.015992
2     12.647009
3     13.799460
4     14.401194
5     15.203605
6     16.712768
7     17.387709
8     18.543462
9     19.185494
10          NaN
dtype: float64

In [241]:
s1.mul(s2)

0           NaN
1     11.808091
2      4.588887
3      2.807563
4      8.982084
5     12.742312
6      4.882946
7     11.021237
8      8.674231
9     16.290128
10          NaN
dtype: float64

In [242]:
s1.div(s2)

0           NaN
1     12.195028
2     36.828105
3     69.811444
4     25.049866
5     20.090546
6     59.185580
7     29.397789
8     41.617523
9     24.554749
10          NaN
dtype: float64

In [243]:
s1.min()

11

In [244]:
s1.max()

20

In [245]:
s1.mean()

15.5

In [246]:
s1.median()

15.5

In [247]:
s1.mode()
# All elements are seen, since no element appears multiple times

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
9    20
dtype: int32

In [248]:
s1.std()

3.0276503540974917

In [249]:
s1.equals(s2)

False

In [250]:
s2 = s1

In [251]:
s2.equals(s1)

True

In [256]:
s5 = pd.Series([1,2,3,4,5,5,5,6,7,7],[1,2,3,4,5,6,7,8,9,10])
s5

1     1
2     2
3     3
4     4
5     5
6     5
7     5
8     6
9     7
10    7
dtype: int64

In [257]:
s5.value_counts

<bound method IndexOpsMixin.value_counts of 1     1
2     2
3     3
4     4
5     5
6     5
7     5
8     6
9     7
10    7
dtype: int64>

**Note:**
Don't need to import Pandas if you are working using Anaconds, if PyCharm or VSCode, it needs to be imported

Advanced topics - 
Bert

Other
Naive bayes algorithm